### ISSUE TITLE
Using MIDI.as submodule, can you merge Dev into Master?

### ISSUE THREAD

**Issue by dcorboy** [mudcube/MIDI.js#105]
Hello Michael,

MIDI.js is awesome and I've incorporated it into an application I'll be publishing on GitHub once I sort out the git submodule issue I'm having.

The problem is that I need USE_XHR (=false) which is in the Dev branch, but I also need the /soundfont directory, which is only in Master.

Trying to incorporate both of these produces a messy submodule relationship and I'd prefer not to fork.

Do you have any plans to merge Dev into the Master branch?

**Comment by mudcube** [comment]
Merged :)
