### ISSUE TITLE
Is it possible to use MIDI.Player without a soundfont?

### ISSUE THREAD

**Issue by bthj** [mudcube/MIDI.js#111]
Hi, I'm wondering if it is possible to use the MIDI.Player without loading a SoundFont?  

Just need the note information for each note played in a MIDI file, via a callback in:

    MIDI.Player.addListener(...)

Tried something like:

    MIDI.loadPlugin(function() {

      player = MIDI.Player;
      player.loadFile( song[songid], player.start );

      player.addListener( midiNotePlayedCallback );

      MIDI.loader.stop();
    });

but get back a Cross origin error (from a request for a SoundFont file that I don't need).

P.s. Asked a similar question here:  http://stackoverflow.com/questions/27192728/receive-note-events-from-a-midi-file-with-javascript

**Comment by hellopath** [comment]
I was coming to ask the same question. Do you find any way for that @bthj ?

Thanks

**Comment by bthj** [comment]
Nope, I haven't yet found a way to do that.

**Comment by mudcube** [comment]
Not unless you're on the Chrome Canary and have WebMIDI flag enabled.
