### ISSUE TITLE
Bug on latest Chrome for OSX at http://mudcu.be/midi-js/

### ISSUE THREAD

**Issue by Sheraff** [mudcube/MIDI.js#120]
![screen shot 2015-01-28 at 01 34 47](https://cloud.githubusercontent.com/assets/1325721/5930285/e17fda54-a68d-11e4-98e6-702a52e7094f.png)

**Comment by billtj** [comment]
And similar thing happens on the latest Chrome (Version 40.0.2214.115 m) for Windows 7.

**Comment by ssorallen** [comment]
The bug seems to be that `createGainNode` has been renamed to `createGain`. There are other changes in the spec as well: https://developer.mozilla.org/en-US/docs/Web/API/Web_Audio_API/Porting_webkitAudioContext_code_to_standards_based_AudioContext

**Comment by Shahor** [comment]
Just here to up this thread :)

**Comment by mudcube** [comment]
The demo has been updated.

I need to merge the dev into master branch, but you can use dev till then.
