### ISSUE TITLE
Is this lib still alive?

### ISSUE THREAD

**Issue by Shahor** [mudcube/MIDI.js#126]
Ping?!

**Comment by uber5001** [comment]
The website http://mudcu.be/midi-js/ appears to be broken, suggesting that maybe this library is no longer updated?

**Comment by mudcube** [comment]
Not dead. There is a refactor of the code in the works. If I could find a free day to finish up it would be ready for release. Unfortunately (or fortunately) I have been so busy with client projects with my company SketchIO there hasn't been time to work on this audio stuff lately.

**Comment by mudcube** [comment]
I pushed the latest dev branch and updated the demo. The demo doesn't have the loader anymore so it will appear like nothing is happening until the sound-font loads, obviously that part of the demo should (and will) be fixed:  http://mudcu.be/github/midi-js/

**Comment by Shahor** [comment]
Thank you @mudcube :]
