### ISSUE TITLE
Error in plugin.webmidi.js. Outputs is not a function.

### ISSUE THREAD

**Issue by anastasiyaShahova** [mudcube/MIDI.js#131]
Don't work this code:
MIDI.loadPlugin({
        soundfontUrl: "./soundfont/",
        instrument: "acoustic_grand_piano",
        onprogress: function(state, progress) {
            console.log(state, progress);
        },
        onsuccess: function() {
  			play();
        }
    });
Error: plugin.webmidi.js:69 Uncaught (in promise) TypeError: object is not a function.
Error occurs in Chrome when enable flag web-midi-api.
Can you help me resolve this problem?

**Comment by mscuthbert** [comment]
Same problem here in Chrome.  Reference pull-request #132

**Comment by pwambach** [comment]
Same here with Chrome 43 on OSX. Your changes from PR #132 did the trick, thx!

**Comment by theKristi** [comment]
Yep, same problem. it worked intermittently for me yesterday. Not today though...

**Comment by muggy8** [comment]
same problem here. wanted to show a friend my website but got this weird error D:

Even your home site doesn't work anymore...

**Comment by muggy8** [comment]
it seems to still work in firefox tho o.o
