### ISSUE TITLE
'could not be decoded.' message in Firefox after loading MIDI plugin

### ISSUE THREAD

**Issue by shivrajsa** [mudcube/MIDI.js#147]
Hello,

When MIDI plugin is loaded, I get below output
"Media resource data:audio/mpeg;base64,/+MYxAAAAANIAUAAAASEEB/jwOFM/0MM/90b/+RhST//w4NFwOjf///PZu////9lns5GFDv//l9GlUIEEIAAAgIg8Ir/JGq3/+MYxDsLIj5QMYcoAP0dv9HIjUcH//yYSg+CIbkGP//8w0bLVjUP///3Z0x5QCAv/yLjwtGKTEFNRTMuOTeqqqqqqqqqqqqq/+MYxEkNmdJkUYc4AKqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqq could not be decoded."

at the end it says 'could not be decoded', my application works fine, but I don't know why it appears, please guide

**Comment by mb2140** [comment]
Take out line 87 in AudioDetect.js - it's basically trying to load play this file to determine if your browser supports it.  Firefox will throw an error in the console.
