### ISSUE TITLE
Not able to play base64 string created using jsmidi

### ISSUE THREAD

**Issue by shivrajsa** [mudcube/MIDI.js#148]
Hello,

I am creating base64 string for sequence of notes using jsmidi
https://github.com/sergi/jsmidi
Here is my string = 'data:audio/mid;base64,TVRoZAAAAAYAAAABAIBNVHJrAAAAhAGRPH88gTx/AJE+fzyBPn8AkUB/PIFAfwCRQn88gUJ/AJFDfzyBQ38AkUV/PIFFfwCRR388gUd/AJFIfzyBSH8AkUh/PIFIfwCRR388gUd/AJFFfzyBRX8AkUN/PIFDfwCRQn88gUJ/AJFAfzyBQH8AkT5/PIE+fwCRPH88gTx/AP8vAA=='

Here is my code to play 
MIDI.Player.loadFile(string);
MIDI.Player.start();

It does not play the string. What could be an issue? Please guide.

Even when I export MIDI file & play, it does not work, but same MIDI file works well with http://mudcu.be/piano/

**Comment by shivrajsa** [comment]
Can anybody please help? I am still struggling to implement this.

**Comment by shivrajsa** [comment]
Issue is solved, it was because of wrong channel number while generating base64 string. Still output is not good, need to look into that

**Comment by tjvg91** [comment]
hello,

i'm new here.

how did you coreclty generate base64 string?

**Comment by shivrajsa** [comment]
Here is link to my desktop application created using MIDI.js, download & unzip.
http://vishwamohini.com/download/vmp-download.php

Refer vm.js at in folder ../assets/vm-js/vm.js.
Refer function "createMidiFile" for building base64 string change value of variable  "channel" to 0 explicitly.
uncomment line "var x = "data:audio/midi;base64," + song.b64;"
Refer "vm-midifile-creator.js" in ../assets/vm-js/ for code
Array.prototype.push.apply(noteEvents, MidiEvent.createNote(noteobj));
and 
var track = new MidiTrack({ events: noteEvents });
            var song  = MidiWriter({ tracks: [track] });
            var track = new MidiTrack({ events: noteEvents });
            var song  = MidiWriter({ tracks: [track] });
Also search & refer array variable "VMP_notetokey" in vm.js to know midi number to note mapping.
Hope that will help.

Here is code to play base64 string
function playMIDIString(string)
    {
MIDI.loadPlugin({
            soundfontUrl: "./soundfont/",
            onprogress: function(state, progress) {
            },
            onsuccess: function() {
                /// this sets up the MIDI.Player and gets things going...
                player = MIDI.Player;
                player.loadFile(string,player.start);
            }
        });
    }
This feature is experimental, please share your code if you enhance it.

**Comment by grimmdude** [comment]
Hi, What channel did you end up using to fix this?  Thanks

**Comment by shivrajsa** [comment]
Sorry for late reply, I used channel 1 to fix this issue.
