### ISSUE TITLE
How to Play different instrument in MIDI player other than piano

### ISSUE THREAD

**Issue by shivrajsa** [mudcube/MIDI.js#158]
I have generated a base64 string using channel 0, this string is successfully played by MIDI Player with Piano sound.
I have more instruments which are mapped on other channels, for Example instrument 105(Sitar) is mapped on channel 8, & I have created base64 string for sitar with channel 8. But it does not work with MIDI player. 

I want MIDI player to dynamically identify instrument & channel set & play accordingly.
How can I achieve that? please guide.

**Comment by gleitz** [comment]
Would you provide some sample code so we can take a look?

**Comment by krisalexander200** [comment]
I am also not getting any non-piano sounds to work, either.

I dropped in the entire kit of recommended pre-generated soundfonts into the local soundfonts directory and initially ran the grand piano as a test. it worked. then I tried to use anything else. no sounds were made.

as a test, i iterated across all notes to see if anything was there. for the grand piano, it started at around note 50. thus, the offset could be set to 50.

however, with everything else, even starting from note 0, was just silence no matter how far up i count.

```
MIDI.loadPlugin({
    soundfontUrl: './soundfont/',
    instrument: "acoustic_guitar_nylon",//"acoustic_grand_piano",
    onprogress: function(state, progress) {
        console.log(state, progress);
    },
    onsuccess: function() {
    console.log("ready");
    $scope.midi.piano = MIDI;


    MIDI.programChange(2, 118);
    MIDI.pianoKeyOffset = 50;
        //for (var n = 0; n < 100; n ++) {
    var n = 0;
    setInterval(function() {


      console.log('ocunting up with notes? (offset: ', MIDI.pianoKeyOffset);
            var delay = n / 4; // play one note every quarter second
            var note = MIDI.pianoKeyOffset + n; // the MIDI note
      //var note = n;
            var velocity = 127; // how hard the note hits
            // play the note
            MIDI.noteOn(0, note, velocity, delay);
            // play the some note 3-steps up
            MIDI.noteOn(1, note + 3, velocity, delay);
      n++;
        }, 150);

    }

}) 
```

**Comment by AEtherSurfer** [comment]
+1 so far only acoustic_grand_piano works.

synth_drum in the Basic.html example doesn't work either.

**Comment by krisalexander200** [comment]
@AEtherSurfer I found the problem / solution. It turns out that the second parameter of MIDI.programChange is actually a number that corresponds to the instrument your'e trying to set.

If you set the string value of the instrument, and don't also set the proper number of the instrument, they don't match, and then it doesn't work.

You can work around this by doing a lookup of the right ID number and then populating it in `programChange`, like this:

``` javascript
var instrumentName = "flute";

MIDI.loadPlugin({
  soundfontUrl: "path/to/instruments/soundfonts/",
  instrument: instrumentName,
  onprogress: function(state, progress) {
    console.log("loading...", state, progress);
  },
  onsuccess: function() {
    MIDI.programChange(0, MIDI.GM.byName[instrumentName].number);
  }
});
```

**Comment by brannondorsey** [comment]
:+1: +1 to @krisalexander for finding and posting this solution. This is a significant bug that should be documented. Thanks!

**Comment by acosme** [comment]
I was able to run "flute" following this:
[https://github.com/mudcube/MIDI.js/issues/97](url)

Don't forget to call "loadPlugin" inside document.ready.

**Comment by silverhawk184** [comment]
@krisalexander200 
Kris was on the right track (or the code has changed between then and now) but the correct syntax is:

    var instrumentName = "flute";

    MIDI.loadPlugin({
      soundfontUrl: "path/to/instruments/soundfonts/",
      instrument: instrumentName,
      onprogress: function(state, progress) {
        console.log("loading...", state, progress);
      },
      onsuccess: function() {
        MIDI.programChange(0, MIDI.GM.byName[instrumentName].program);
     }
    });

was: MIDI.GM.byName[instrumentName].number
now: MIDI.GM.byName[instrumentName].program

**Comment by Owwwl9** [comment]
For me MIDI.GM.byName[instrumentName].number does still work, while MIDI.GM.byName[instrumentName].program does not. 

However I struggle with getting the right instruments at the right channel. I want to be able to practically load any MIDI file, thus I need a flexible syntax to adjust to and play different instruments. So far I tried:

```
var instruments;

player.loadFile("test.mid", function () {
    instruments = player.getFileInstruments();
    for (var i = 0; i < instruments.length; i++) {
        MIDI.programChange(i, MIDI.GM.byName[instruments[i]].number);
    }
});
```

at least I get all instruments playing that way, but they seem to either somehow play on the wrong channel or the wrong soundfont is assigned. I haven't been able to figure it out yet.

Any ideas?
