### ISSUE TITLE
How to add event listener and animation for sequence of notes

### ISSUE THREAD

**Issue by shivrajsa** [mudcube/MIDI.js#164]
For many reasons I can not use MIDI player, I have sequence of notes in loop how can I add event listener and animation on individual notes.I tried with `setTimeout()` but it does not synch with sequence.

```
function play(){
    for (var i=0;i<=1;i++)
    {
      for (var j=0;j<=32;j++)
      {
       if(composition[i][j]!=40)
       {
         MIDI.noteOn(0, composition[i][j], velocity, delay);
        }
       else if(composition[i][j]==40)
        {
          MIDI.noteOff(0, composition[i][j],velocity, delay);
        }
        delay=delay+0.1;
         }
       }
      }
```

**Comment by CepheiA** [comment]
+1

**Comment by shivrajsa** [comment]
Even a hint may help to get right direction, please guide.

**Comment by gleitz** [comment]
Here's an [example of animation working with noteOn](https://gist.github.com/gleitz/cb4d40a52e1b2043bfcb). It wold be nice if noteOn had a callback, but this will work in its place.
