### ISSUE TITLE
How to export sequence of notes in MP3 or WAV format?

### ISSUE THREAD

**Issue by shivrajsa** [mudcube/MIDI.js#169]
How can we export MP3 (or similar format) of sequence of notes, we are playing through MIDI.js.

I am successful in exporting it in MIDI format, but it always plays piano notes when played in windows player.

I am playing other instruments through MIDI.js so I want to record actual output produced by MIDI.js.

**Comment by ccarpita** [comment]
This wouldn't be too hard to implement using the [MediaRecorder](http://caniuse.com/#search=MediaRecorder) API which is supported on FF/Chrome, along with [createMediaStreamDestination](https://developer.mozilla.org/en-US/docs/Web/API/AudioContext/createMediaStreamDestination).  What it would require for this library is:

A) The final effects/gain node to be exposed via the API
or
B) An API to provide additional destination nodes
or
C) Support for MediaRecorder within MIDI.js with an API like `recordStart` and `recordStop`, where the latter would provide the data buffer as a return value.

Not sure which the author(s) would prefer.

**Comment by shivrajsa** [comment]
@ccarpita Thank you for your guidance.
I am able to implement that when browser is making sound.

I am wondering if there is there any way to achieve this without actually playing  buffer source. :-)
Means only buffer of noteOn anf noteOff will be the input.

Actually I am playing many notes with noteOn anf noteOff, in this case I am not able to implement MIDI player. I tried to implement it by creating MIDI file & giving that as input for MIDI player but result is not good.

Final objective is to implement player with [ stop / pause etc ] options for sequence of notes which are played by noteOn & noteOff

**Comment by Jandou6** [comment]
@shivrajsa  Do you find any way to export  mp3.  I have this problem now~ help

**Comment by shivrajsa** [comment]
@Jandou6 I am able to implement it when browser is making sound. Means we have to press button to start recording when we are sure that browser is making sound.

**Comment by Jandou6** [comment]
@shivrajsa But if I use browser to record the sound. It will use microphone to recorder,So it will record the other voice such as the people speaking.And if I use earphone to play the sound that the microphone will record nothing.

**Comment by shivrajsa** [comment]
@Jandou6 please refer this gist [https://gist.github.com/shivrajsa/b4e4467a21420e74638b650a3c4b3bac](https://gist.github.com/shivrajsa/b4e4467a21420e74638b650a3c4b3bac) I have modified plugin.webaudio.js for mp3 recording and button to call start and stop transaction.
follow these four variables in the gist `var recordchunks=[];
		var recorderdest = null;
		var mediaRecorder = null;
		var isrecord = 1;` to understand code. There could be better way to do that, I am not expert.
Also refer midi.html  for button start and stop
You can start recording only when browser is making sound.
