### ISSUE TITLE
MIDI Tuning Standard support

### ISSUE THREAD

**Issue by infojunkie** [mudcube/MIDI.js#181]
I'd like to retune the MIDI notes to support microtonal scales, just intonation, etc. I understand that MIDI Tuning Standard (MTS) is the vehicle to achieve this. Is MTS supported here? Otherwise, can anyone give a hint to how the implementation would proceed?

**Comment by shivrajsa** [comment]
#179 this question may help you.

**Comment by infojunkie** [comment]
Yes, thanks, it helps. I guess the tuning standard is not implemented and implementing it would end up using similar logic to the individual detune operation.
