### ISSUE TITLE
Effects module not installed.

### ISSUE THREAD

**Issue by martyquinn** [mudcube/MIDI.js#197]
I tried to do this call in the onsuccess javascript method. 
MIDI.setEffects([ {
        type: "Convolver",
        highCut: 22050, // 20 to 22050
        lowCut: 20, // 20 to 22050
        dryLevel: 1, // 0 to 1+
        wetLevel: 1, // 0 to 1+
        level: 1, // 0 to 1+, adjusts total output of both wet and dry
        impulse: "Midi.js-master/inc/tuna/impulses/impulse_rev.wav", // the path to your impulse response
        bypass: 0
    } ]);

And I am receiving this message: effects module not installed. 
How can I install the effects module? I would like to add reverb to the output.

**Comment by shivrajsa** [comment]
It seems you have not added Tuna.js. could you please check

**Comment by martyquinn** [comment]
Yes, you're right. I didn't realize I had to add it to the list of javascript libraries included at the top of my html. 

Line added that solved it: 
    <script src="Midi.js-master/inc/tuna/tuna.js" type="text/javascript"></script>
Thank you.
