### ISSUE TITLE
How to pre schedule notes ?

### ISSUE THREAD

**Issue by shivrajsa** [mudcube/MIDI.js#199]
Please refer #61 Where @mudcube says that 

> You should be prescheduling the notes out in advance. Do this in sets of say 500 notes (for instance), and then once those notes are done (or better yet a few seconds before they're done playing) schedule another chunk of notes. 

Could anybody share an example to achieve pre scheduling of the notes. 

I assume this will reduce load on CPU while playing notes & user can play long sequence of notes smoothly. Correct me if my assumption is wrong.

I am using noteOn & noteOff to play sequence of notes. When I play long sequence of notes with low configuration machine, browser struggles to play it smoothly

**Comment by midixman** [comment]
Hi,

I think the best tutorial on pre-scheduling notes is [A Tale of Two Clocks - Scheduling Web Audio with Precision](https://www.html5rocks.com/en/tutorials/audio/scheduling/).

You can see an example in a project that I just started: [WebAM](https://github.com/midixman/webam). It is in the MusicEngine part.

Best regards,

Bill
