### ISSUE TITLE
No more maintained ?

### ISSUE THREAD

**Issue by Adrion** [mudcube/MIDI.js#202]
2 years of inactivity, 16 PR and 86 issues that's sad...

**Comment by shivrajsa** [comment]
Yes, that is sad, I think someone has to take initiative to maintain parallel fork to test and  merge pull requests.
I am not expert developer otherwise I would have done that.

**Comment by Adrion** [comment]
You may add Maintainers for midi.js.
Or create and organisation, move this project into and add people who wants to help :)

You have to many stars on this one. 
It would be sad to leave it ^^

I'd like to help btw ;)

**Comment by Adrion** [comment]
sry @shivrajsa  I thought you're were @mudcube 

But yeah as I said if @mudcube is too busy, an organisation can be created to allow some peoples to help & check PR's

**Comment by shivrajsa** [comment]
Yes, but someone, who has rights, has to take that initial step

**Comment by Adrion** [comment]
The author seems pretty active on github, we'll see if he will come here. :)

**Comment by Adrion** [comment]
@mudcube ? :)

**Comment by ryanreece** [comment]
Hey folks here! I work with @mudcube and we are working on continuing to maintain MIDI.js. We now have a couple more contributors and will begin pushing updates and responding to pull requests in the coming weeks. Stay tuned and I want you to know that MIDI.js is still alive! 😄

**Comment by Adrion** [comment]
Yeaaah many thanks :D !

**Comment by shivrajsa** [comment]
@ryanreece I am wondering when will this library come under active development ?

**Comment by mk-pmb** [comment]
> I am wondering when will this library come under active development ?

My guess: As soon as someone needs it. For my project, it looked promising at first, but then I found it's easier to use just parts of the feature set via smaller, more specialized packages.

**Comment by Otto-AA** [comment]
Hey there,
as this seems not to be maintained anymore and I needed different/more features I have created my own version of this. Mine is only for reading midi files and listening to events, but not playing sounds (useful for visualization).

If you want, you can contribute there, or we can also fork the complete midi.js and maintain it, I'd love to see both happen :)

You can view and contribute to my project [here](https://github.com/Otto-AA/MidiPlayer)

**Comment by mk-pmb** [comment]
> but not playing sounds

In that case, the name MidiPlayer is a bit confusing. I'd rather call it MidiReader or something. If someone needs audio output, they could combine it with [sample-player](https://github.com/danigb/sample-player); I've [set out](https://github.com/danigb/sample-player/issues/4#issuecomment-325774066) to research possibilities for shrinking the sound font files, but haven't found enough time yet.

**Comment by Otto-AA** [comment]
@mk-pmb Yeah, I also considered that name, but I feel like MidiPlayer plays a midi so one can listen to the events (listen in the coding way,  not audio^^) and MidiReader just parses it to an object without functions like play, pause, setSpeed, etc.

And thanks for mentioning the [sample-player](https://github.com/danigb/sample-player), seems useful :)

**Comment by mk-pmb** [comment]
> listen to the events

That I'd call "subscribe to". Maybe MidiBurner because it "fires" events? Or just generic MidiEmitter.

**Comment by Otto-AA** [comment]
@mk-pmb Yeah, I will definitely consider these options (MidiBurner sounds nice), but I think we shouldn't discuss it here. You can create an issue on the projects site if you want to add something to this topic.

**Comment by Adrion** [comment]
All pinned projects from Mudcube are 3+ years old and no more and dead... He seems to work only on private projects now. Sad...
Please make a maintainer team. 
I close this issue...

**Comment by shivrajsa** [comment]
@ryanreece  You had promised to keep this alive. We are waiting for merger of all PRs.

**Comment by mscuthbert** [comment]
Would a move to maintaining under the Rejuvenate project (https://github.com/rejuvenate/rejuvenate) be of value?  See https://github.com/rejuvenate/rejuvenate/issues/5

**Comment by hmoffatt** [comment]
> Would a move to maintaining under the Rejuvenate project (https://github.com/rejuvenate/rejuvenate) be of value? See [rejuvenate/rejuvenate#5](https://github.com/rejuvenate/rejuvenate/issues/5)

I'm not so sure. The project needs a leader or a core team who know the code well. Some of the fixes proposed in some of the issues are wrong and allowing a free for all on the code would not be a good outcome.

**Comment by TPS** [comment]
My apologies on the late reply. 🙇🏾‍♂️

Who here would actively maintain a fork?  I'd be happy to open 1 up per https://github.com/rejuvenate/rejuvenate/issues/5.  Also, if anyone _already_ maintains a more-active fork (but doesn't want sole-maintainer responsibilities), I'd consider candidates to fork _from_.

**Comment by mscuthbert** [comment]
I have created an ES6-modern standards version of MIDI.js at https://github.com/mscuthbert/midicube and happy to take PRs there.  Also happy to make major contributors to this Repo admin on the midicube repo to prevent this from happening again.
