### ISSUE TITLE
how can i save as a file,

### ISSUE THREAD

**Issue by Jandou6** [mudcube/MIDI.js#203]
I use midi.js to create a music~ and i don't know how to save as a file,can somebody help me ? And what the type of this file support? 

or can i save as mp3 file? or must save as midi file. 

i want to save this file in cdn, so that i can use this file in every web that i need.

**Comment by shivrajsa** [comment]
@Jandou6 You can create midi file using this lilrary [https://github.com/sergi/jsmidi](https://github.com/sergi/jsmidi)
