### ISSUE TITLE
Correct way to play sequence of notes

### ISSUE THREAD

**Issue by shivrajsa** [mudcube/MIDI.js#205]
I have a sequence of notes with delay data.
I trigger this sequence of notes using `noteOn `function and I loop function `noteOn `for number of notes.

Manytimes, result is not good and notes do not play as they come in sequence. 
Some ending notes and some starting notes start playing together when loop is started,  because of this result is not good for few seconds in the starting.

Can anybody guide what is correct way to play sequence of notes 

Here is code sample

```
var notes = [67, 78, 67 ,67,90, 56,..,...,....]
var delay = [.........]
for(var i=0; l < notes.length; i++)
{
MIDI.noteOn(channel, notes[i], velocity, delay[i]);
}
```

**Comment by DoomTay** [comment]
How is delay determined?

I've found that if delay is replaced with i or `i + MIDI.getContext().currentTime`, that will cause the notes to play in sequence

**Comment by shivrajsa** [comment]
Delay value is managed correctly, it changes for every iteration,  I have just shown it as representative of time value

**Comment by GeorgeKesaev** [comment]
Hey, i didn't understand the fix. 
Can you please explain how to play an array of notes one after another?
Thank you.

**Comment by DoomTay** [comment]
Hm...what does `MIDI.api` say? What browser are you using?

I've found that when it comes to Audio Tag mode, the timing of notes tends to be very, very sloppy.

**Comment by shivrajsa** [comment]
Thanks @DoomTay , your solutions works.
Here is how I have implemented it.
```
var notes = [67, 78, 67 ,67,90, 56,..,...,....];
var delay = [.........],tmpdelay=0;
var ctxtime = MIDI.getContext().currentTime;
for(var i=0; l < notes.length; i++)
{
MIDI.noteOn(channel, notes[i], velocity, ctxtime+tmpdelay);
tmpdelay = tmpdelay + delay[i]
}
```
@rbdedu hope this helps you too.

**Comment by jtrunick** [comment]
I'm looking to do something similar. I'm puzzled though, is this going to play right away? Can you still use the player to start/stop/pause?
