### ISSUE TITLE
How to automate startRecording and stopRecording 

### ISSUE THREAD

**Issue by shivrajsa** [mudcube/MIDI.js#213]
Please refer this issue https://github.com/mudcube/MIDI.js/issues/169
I want to record the sound made by MIDI.js as soon as it starts making sound

I am partially successful to achieve this. Means I have buttons to start and stop recording when MIDI.js is making sound please refer below gist

[https://gist.github.com/shivrajsa/b4e4467a21420e74638b650a3c4b3bac](https://gist.github.com/shivrajsa/b4e4467a21420e74638b650a3c4b3bac)

But I want it to be automatic i.e. recording should start automatically as soon as MIDI.js starts making sound and it should stop automatically when it stops. It should not require manual buttons to control recording.

Please guide to achieve this

**Comment by gleitz** [comment]
In the `onsuccess` of MIDI.loadPlugin you could call MIDI.startRecording. You could also call `startRecording` before the first note is played with `MIDI.noteOn`

**Comment by shivrajsa** [comment]
@gleitz , main challenge is to automate `stopRecording()`, structure of my code is similar to 

```
Function playMelody(....)
{
playNoteSequence1(arrayofnotes,arrayofdelay)
playNoteSequence2(arrayofnotes,arrayofdelay)
playNoteSequence3(arrayofnotes,arrayofdelay)
}
```

and I want to implement

```
Function playMelody(....)
{
playNoteSequence1(arrayofnotes,arrayofdelay)
playNoteSequence2(arrayofnotes,arrayofdelay)
playNoteSequence3(arrayofnotes,arrayofdelay)
MIDI.stopRecording();
}
```
I have implemented `startRecording()` in `MIDI.noteOn()` function in plugin.webaudio.js, here is the [Gist](https://gist.github.com/shivrajsa/b4e4467a21420e74638b650a3c4b3bac)

It seems `stopRecording()` is called before completion of` playNoteSequence3(arrayofnotes,arrayofdelay)`, I think it is because of asynchronous execution of functions.

**Comment by gleitz** [comment]
You should put the `stopRecording` in the callback of `playNoteSequence3`, after calling the final `noteOff`

**Comment by shivrajsa** [comment]
@gleitz , I provided incomplete information, sorry for that. Actually I want to execute `stopRecording()` after execution of all three function `playNoteSequence1(arrayofnotes,arrayofdelay)` `playNoteSequence2(arrayofnotes,arrayofdelay)` `playNoteSequence3(arrayofnotes,arrayofdelay)`

Because all these three functions execute asynchronously. Is there any way to achieve that.

Also I am thinking about calculating the time of whole melody based on tempo and schedule `stopRecording()` accordingly, but it will be little complex solution.

**Comment by shivrajsa** [comment]
@gleitz , I am successful to implement  stop recording by scheduling `stopRecording()` using `setTimeout`

**Comment by gleitz** [comment]
Awesome! Maybe you can post some sample code for others who might have this issue :)

**Comment by shivrajsa** [comment]
I have array of delay for each note in miliseconds 

`var delayarray = [500,500,1000,  . . . . .] `

I add all these delay to calculate total time of melody, and call `stopRecording()` using `setTimeout`

`setTimeout(MIDI.stopRecording,totaltime+1000)`
