### ISSUE TITLE
Export MP3 from Midi File without playing

### ISSUE THREAD

**Issue by LambdaDigamma** [mudcube/MIDI.js#214]
Hi,

is there any opportunity for exporting the midi as a mp3 file (or something similar) rather than playing it back in the browser? (I'm in a Node.js environment so I'm not able to record played audio like in [this example](https://gist.github.com/shivrajsa/b4e4467a21420e74638b650a3c4b3bac))
I need to return the url of a upload audio file to a web service so I have to write it to a file.

Thanks in advance!
~ LambdaDigamma

**Comment by CaptainSP** [comment]
Hello! You can use `MIDI.Player.data` variable for read data without play. 
You can access notes with it. 
After do that you can get base64 audio file with `MIDI.Soundfont.acoustic_grand_piano.A0` (A0 is Note name).
