### ISSUE TITLE
How come this simple example does not work on iOS?

### ISSUE THREAD

**Issue by linkenmin** [mudcube/MIDI.js#221]
[Code]
MIDI.loadPlugin({
	soundfontUrl:'../soundfont/',
	instrument:'acoustic_guitar_steel',
	onsuccess:function() {
		console.log('MIDI is ready.');
		MIDI.programChange(0, 25);
		setInterval(function() {
			console.log('play');
			MIDI.noteOn(0, 60, 126);
		}, 1000);
	}
});

It thought it would play note "60" per second, but no sound on iOS.
Does anyone have the answer?
Thanks a lot!

**Comment by linkenmin** [comment]
[Root Cause]
https://github.com/mudcube/MIDI.js/issues/80

**Comment by hmoffatt** [comment]
You didn't mention iOS originally. Your code worked with the right note on other browsers.
