### ISSUE TITLE
Use with NPM + Browserify?

### ISSUE THREAD

**Issue by NHQ** [mudcube/MIDI.js#24]
Greetings,

This is an impressive thing here, but I find it to be confusing almost completely unportable. 

Please consider using [NPM](http://npmjs.org), and perhaps [browserify](https://github.com/substack/browserify), to make it truly modular and portable. It  much easier to manage and organize code with those tools (which are becoming industry standards in Javascript).

Many thanks,

**Comment by lukehorvat** [comment]
@timaschew Doesn't seem to work. The `main` property of `package.json` references a file in the `build` directory. For whatever reason, this directory is listed in `.gitignore`, so NPM doesn't download it.

@mudcube Care to remove that directory from `.gitignore`?

**Comment by timaschew** [comment]
That's right, the `package.json` is only made for developing MIDI.js.
And it also doesn't make sense to point the main file to the source, because everyhting is just using the global scope instead of using `require`.

**Comment by okaybenji** [comment]
NPM support would be really helpful! I'm trying to use MIDI.js with NPM and Browserify in order to send events from MIDI files to a Web Audio synthesizer.

**Comment by hoqqanen** [comment]
+1 to NPM support -- it's the sane way to manage dependencies in builds of modern single-page apps.

**Comment by NHQ** [comment]
https://github.com/NHQ/midi-file-parser

**Comment by andybarron** [comment]
Any updates on this? NPM is used quite often for front-end dev (usually through webpack, browserify, et al). ~~Wrapping the library in [UMD](https://github.com/umdjs/umd) and~~ publishing to NPM would be great.

Edit: Looks like there's already a UMD bit, so this might work via install through NPM+GitHub, but proper NPM support would still be nice :)

**Comment by turigeza** [comment]
npm install https://github.com/mudcube/MIDI.js/ seems to do the trick

**Comment by Zulko** [comment]
@turigeza Have you managed to use MIDI.js with "npm install" ? In my case the installation works, but the package can't be loaded.

**Comment by okaybenji** [comment]
Just want to throw in my 2 cents for folks who wind up here: In the end I decided to write my own handling for the Web MIDI API, and it turned out to be pretty easy and straight-forward. MIDI.js would have been overkill for my purposes. Check out this article if you think rolling your own might work for you: [smashingmagazine.com/2018/03/web-midi-api](https://www.smashingmagazine.com/2018/03/web-midi-api/)
