### ISSUE TITLE
There is no sound when I am playing my own midi file

### ISSUE THREAD

**Issue by ShuyiZhou495** [mudcube/MIDI.js#254]
Hi,
When I am using the midi files provided by the demos, there is actually sound. But when I am playing my midi file generated by python mido library, there is no sound. I am sure my midi file is right because it can be played using python pygame library or transfer into wav file correctly.

And I have included the acoustic_grand_piano-ogg.js and acoustic_grand_piano-mp3.js as <script>

Here is my code
```      MIDI.loader = new sketch.ui.Timer;
	eventjs.add(window, "load", function(event) {
		MIDI.loader = new sketch.ui.Timer;
		MIDI.loadPlugin({
			soundfontUrl: "./static/soundfont/",
			instrument: "acoustic_grand_piano",
			onprogress: function(state, progress) {
				MIDI.loader.setValue(progress * 100);
			},
			onsuccess: function() {
				player = MIDI.Player;
				player.timeWarp = 1; // speed the song is played back
				player.loadFile(song, player.start);
			}
		});
	});

The base64 string of the song is attached in song.txt. [song.txt](https://github.com/mudcube/MIDI.js/files/4535926/song.txt)
Do you have some idea on this problem?
Thank you very much!

**Comment by hmoffatt** [comment]
I think you are loading the acoustic piano (program 0) but your MIDI file is using program 1. Try loading the bright acoustic piano (program 1) as well.

**Comment by ShuyiZhou495** [comment]
> I think you are loading the acoustic piano (program 0) but your MIDI file is using program 1. Try loading the bright acoustic piano (program 1) as well.

That's it! Thank you very much!
