### ISSUE TITLE
ReferenceError: Base64Binary is not defined

### ISSUE THREAD

**Issue by pgulley** [mudcube/MIDI.js#266]
As in title- trying to get midi.js running in a simple browser application.
Still just in the 'getting used to this library' phase- I'm essentially working with the 'base' demo file. 
When loading in a soundfont file, the library crashes with the above error. 

Running on Firefox

**Comment by SamirDhoke** [comment]
i think you need to include the ![Base64Binary](https://github.com/mudcube/MIDI.js/blob/master/inc/shim/Base64binary.js) script.
