### ISSUE TITLE
Play MIDI with multiple instruments 

### ISSUE THREAD

**Issue by mbektimirov** [mudcube/MIDI.js#3]
Is it possible to bind different instruments to each channel in multichannel MIDI? For example if I've got a midi file with guitar and drums and soundfonts for each instrument. How could I play this midi in this way? Should i hack jasmid or MIDI.js and add instruments support for each midi channel?

Thanks.

**Comment by spencerhitch** [comment]
I have some questions about the functionality of this:

It seems to me `programChange` sets one instrument on a channel but `loadPlugin` can load multiple soundfonts with the `instruments` attribute.

How would `programChange` be called in a way that when `noteOn` get called it can sound with different instrument types?
