### ISSUE TITLE
about size of generated soundfont

### ISSUE THREAD

**Issue by AngelDoReMi** [mudcube/MIDI.js#42]
Hi,
I use soundfont_builder.rb and FluidR3_GM.sf2(download from fluidsynth sourceforge site,114M), it works perfect on my win7(no error or warning msg).but i found the generated soundfont js file size is smaller than soundfonts in git. for example,acoustic_grand_piano-mp3.js in git is 1402 KB,but my acoustic_grand_piano-mp3.js is only 88KB.
my question is why? is it because my generated soundfonts not completely? or because the sample soundfonts generated from a more high-quality sound bank?

i really wants a "high-quality" guitar soundfonts(i like the sample acoustic_grand_piano-mp3.js) ,any sugguestion?
thanks!

**Comment by mk-pmb** [comment]
Additional discussion about output file sizes can be found in #218 .
