### ISSUE TITLE
iOS compatible

### ISSUE THREAD

**Issue by andruo11** [mudcube/MIDI.js#80]
Hello - I love this library. I was wondering why http://mudcu.be/midi-js/ doesn't work as-is on the iPhone -- does it have to do with the way the OS restricts audio playback to being in response to a direct user action (a click or some interaction with the web page)? It looks like this was the old issue item #1 4 years ago, before the WebAudio support was added to Safari.

**Comment by kaiowa** [comment]
i have problems with this issue, where should i put  a click event 

inside  MIDI.loadPlugin,  onsuccess event ?

could you provide and example plz?

Many thanks

**Comment by andruo11** [comment]
Hi Kaiowa, I think you have to do it like this because of Apple’s user interaction & sound policy for the iPhone, that playing sound on a page for the first time has to be in direct response to user input. After they click on the button in the example, noteOn can come from anywhere. Onsuccess does have to have fired before the click happens.

<input type=“button” onclick=“test();”></input>

<script>
function test() {
   MIDI.noteOn(…)
}
</script>
