### ISSUE TITLE
Main website demo not working on OS X 10.10 (Yosemite) w/ Safari 8 or Chrome

### ISSUE THREAD

**Issue by mscuthbert** [mudcube/MIDI.js#93]
The main mudcu.be MIDI.js site is not working for me after an upgrade to the Yosemite beta on either Safari 8 (it says "Loading API" but no dimming or loading of soundfonts occurs) or Chrome 36.0.1985.125 (dims the lights, says loading Soundfonts, gets to C8 and then stalls).  The Chrome version gives an Uncaught TypeError at line 83 of MIDI.Plugin.js where "var gainNode = ctx.createGainNode();"  The Safari problem seems to be intermittent; sometimes it works sometimes not.  The timing and playback quality when Safari 8 works seems to be improved, closer to Chrome than before.

Firefox 31 works fine on Yosemite beta, though it still has terrible timing problems from the HTML5 <audio> tag.

**Comment by mudcube** [comment]
Dev merged with master. Issue should be solved.
